package org.judal.transaction;

/**
 * © Copyright 2016 the original author.
 * This file is licensed under the Apache License version 2.0.
 * You may not use this file except in compliance with the license.
 * You may obtain a copy of the License at:
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.
 */

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Map.Entry;
import java.util.concurrent.ConcurrentHashMap;

import javax.transaction.xa.XAException;
import javax.transaction.xa.XAResource;
import javax.transaction.xa.Xid;

/**
 * <p>Implementation of javax.transaction.xa.XAResource interface.</p>
 * @author Sergio Montoro Ten
 * @version 1.0
 */
public abstract class TransactionalResource implements XAResource {

	private Xid id;
	private int flags;
	private long created;
	private int timeout;
	private boolean prepared;

	private static ConcurrentHashMap<Xid,LinkedList<TransactionalResource>> resources = new ConcurrentHashMap<Xid,LinkedList<TransactionalResource>>();

	/**
	 * <p>Constructor.</p>
	 * Create a new TransactionalResource using an autogenerated javax.transaction.xa.Xid
	 */
	public TransactionalResource() {
		this(new TransactionId());
	}

	/**
	 * <p>Constructor.</p>
	 * Create a new TransactionalResource using the given javax.transaction.xa.Xid
	 * @param tid Xid
	 */
	public TransactionalResource(Xid tid) {
		id = tid;
		prepared = false;
		timeout = -1;
		created = System.currentTimeMillis();
		LinkedList<TransactionalResource> list;
		if (resources.containsKey(tid)) {
			list = resources.get(tid);
			list.add(this);
		} else {
			list = new LinkedList<TransactionalResource>();
			list.add(this);
			resources.put(tid, list);
		}
	}
	
	protected abstract void startResource(int flags) throws XAException;
	
	protected abstract int prepareResource() throws XAException;

	protected abstract void commitResource() throws XAException;

	protected abstract void rollbackResource() throws XAException;
	
	protected abstract void endResource(int flag) throws XAException;

	public abstract boolean setTransactionTimeout(int seconds);
	
	/**
	 * @return Xid
	 */
	public Xid getId() {
		return id;
	}

	/**
	 * <p>List resources participating in a transaction.</p>
	 * @param tid Xid Transaction id
	 * @return Unmodifiable List&lt;TransactionalResource&gt;
	 * @throws XAException
	 */
	public List<TransactionalResource> listResourcesForTransaction(Xid tid) throws XAException {
		if (!resources.containsKey(tid))
			resources.put(tid, new LinkedList<TransactionalResource>());
		return Collections.unmodifiableList(resources.get(tid));
	}

	/**
	 * @param tid Xid
	 * @param onePhase boolean
	 * @throws XAException
	 */
	@Override
	public void commit(Xid tid, boolean onePhase) throws XAException {
		commitResource();
		prepared = false;
	}

	/**
	 * @param tid Xid
	 * @param onePhase boolean
	 * @throws XAException
	 */
	@Override
	public void end(Xid tid, int onePhase) throws XAException {
		endResource(onePhase);
		prepared = false;
		if (resources.containsKey(tid))
			resources.get(tid).remove(this);
	}

	/**
	 * @param tid Xid
	 * @throws XAException
	 */
	@Override
	public void forget(Xid tid) throws XAException {
		if (resources.containsKey(tid))
			resources.get(tid).remove(this);
	}

	/**
	 * @return int
	 * @throws XAException
	 */
	@Override
	public int getTransactionTimeout() throws XAException {
		return timeout;
	}

	/**
	 * @param res XAResource
	 * @return boolean <b>true</b> if res is instance of TransactionalResource
	 * @throws XAException
	 */
	@Override
	public boolean isSameRM(XAResource res) throws XAException {
		return res instanceof TransactionalResource;
	}

	/**
	 * <p>Prepare resource.</p>
	 * @param tid Xid
	 * @throws XAException
	 * @return int XA_OK
	 */
	@Override
	public int prepare(Xid tid) throws XAException {
		prepareResource();
		return XA_OK;
	}

	@Override
	public Xid[] recover(int flag) throws XAException {
		ArrayList<Xid> list = new ArrayList<Xid>();
		for (Entry<Xid,LinkedList<TransactionalResource>> branch : resources.entrySet()) {
			if (branch.getValue().peekFirst().prepared)
				list.add(branch.getKey());
		}
		return list.toArray(new Xid[list.size()]);
	}

	/**
	 * <p>Rollback resource.</p>
	 * @param tid Xid
	 * @throws XAException
	 */
	@Override
	public void rollback(Xid tid) throws XAException {
		rollbackResource();
	}

	/**
	 * <p>Start resource.</p>
	 * @param tid Xid
	 * @param flag int
	 * @throws XAException
	 */
	@Override
	public void start(Xid tid, int flag) throws XAException {
		startResource(flag);
	}

}
